routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
})->name('home');

Auth::routes();

Route::group(['prefix' => 'dashboard', 'middleware' => 'auth'], function() {
    Route::get('/', 'DashboardController@index')->name('dashboard.index');
    Route::get('manual', 'DashboardController@manual')->name('dashboard.manual');

    Route::resource('users', 'UserController');

    Route::resource('roles', 'RoleController');

    Route::resource('parts', 'PartController');

    Route::resource('customers', 'CustomerController');

    Route::resource('warehouses', 'WarehouseController');

    Route::resource('racks', 'RackController');

    Route::resource('shelves', 'ShelfController');

    Route::resource('suppliers', 'SupplierController');

    Route::resource('statuses', 'StatusController');

    Route::resource('orders', 'OrderController');

    Route::get('cart', 'CartController@index')->name('cart.index');
    Route::get('cart/{part}/edit', 'CartController@edit')->name('cart.edit');
    Route::post('cart/{part}/add', 'CartController@add')->name('cart.add');
    Route::put('cart/{part}', 'CartController@update')->name('cart.update');
    Route::delete('cart/{part}', 'CartController@destroy')->name('cart.destroy');

    Route::resource('assignments', 'AssignmentController');
    Route::get('assignments/{assignment}/export', 'AssignmentController@export')->name('assignment.export');

    Route::resource('tasks', 'TaskController');

    Route::resource('categories', 'CategoryController');

    Route::get('time-registrations', 'TimeRegistrationController@index')->name('time-registrations.index');
    Route::post('time-registrations', 'TimeRegistrationController@store')->name('time-registrations.store');
    Route::get('time-registrations/{assignment}/create/', 'TimeRegistrationController@create')->name('time-registrations.create');
    Route::get('time-registrations/{time_registration}', 'TimeRegistrationController@show')->name('time-registrations.show');
    Route::put('time-registrations/{time_registration}', 'TimeRegistrationController@update')->name('time-registrations.update');
    Route::delete('time-registrations/{time_registration}', 'TimeRegistrationController@destroy')->name('time-registrations.destroy');
    Route::get('time-registrations/{time_registration}/edit', 'TimeRegistrationController@edit')->name('time-registrations.edit');

    Route::get('used-parts', 'UsedPartController@index')->name('used-parts.index');
    Route::post('used-parts/{assignment}', 'UsedPartController@store')->name('used-parts.store');
    Route::get('used-parts/{assignment}/create/', 'UsedPartController@create')->name('used-parts.create');
    Route::put('used-parts/{used_part}', 'UsedPartController@update')->name('used-parts.update');
    Route::delete('used-parts/{used_part}', 'UsedPartController@destroy')->name('used-parts.destroy');
    Route::get('used-parts/{used_part}/edit', 'UsedPartController@edit')->name('used-parts.edit');

    Route::resource('units', 'UnitController');
});

resources/views/warehouses/create.blade.php
@extends('layouts.app')
@section('title', __('model.add', ['model' => trans_choice('model.Warehouse', 1)]))

@section('content')

<form method="POST" action="{{ route('warehouses.store') }}">
    @csrf
    <div class="row">
        <div class="xs12">
            <a href="{{ route('warehouses.index') }}" class="button button--contained button--contained--icon-left">
                <i class="material-icons icon">arrow_back</i>
                {{ __('model.back', ['page' => trans_choice('model.warehouse', 2)]) }}
            </a>
        </div>

        <div class="xs12 sm6 md3">
             <div class="row padding--0">
                 <h5 class="xs12">{{ trans_choice('model.Warehouse', 1) }}</h5>

                <div class="xs12">
                    <div class="text-field text-field--filled {{ $errors->has('name') ? 'text-field--helper-text text-field--invalid' : '' }}">
                        <input id="name" type="text" class="text-field__input" name="name" value="{{ old('name') }}" required autofocus>
                        <label for="name" class="text-field__label">{{ __('model.name', ['model' => trans_choice('model.Warehouse', 1)]) }}*</label>

                        @if ($errors->has('name'))
                            <span class="text-field__helper-text" role="alert">
                                {{ $errors->first('name') }}
                            </span>
                        @endif
                    </div>
                </div>
             </div>
        </div>

        <div class="xs12">
            <button type="submit" class="button button--contained button--contained--icon-left">
                <i class="material-icons icon">save</i>
                {{ __('model.add', ['model' => trans_choice('model.Warehouse', 1)]) }}
            </button>

            <button type="reset" class="button button--text button--text--icon-left">
                <i class="material-icons icon">settings_backup_restore</i>
                {{ __('model.reset') }}
            </button>
        </div>
    </div>
</form>
@endsection

resources/views/warehouses/edit.blade.php
@extends('layouts.app')
@section('title', __('model.edit_title', ['name' => $warehouse->name, 'model' => trans_choice('model.warehouse', 1)]))

@section('content')

    <form method="POST" action="{{ route('warehouses.update', $warehouse->id) }}">
        @method('put')
        @csrf

        <div class="row">
            <div class="xs12">
                <a href="{{ route('warehouses.index') }}" class="button button--contained button--contained--icon-left">
                    <i class="material-icons icon">arrow_back</i>
                    {{ __('model.back', ['page' => trans_choice('model.warehouse', 2)]) }}
                </a>
            </div>

            <div class="xs12 sm6 md3">
                <div class="row padding--0">
                    <h5 class="xs12">{{ trans_choice('model.Warehouse', 1) }}</h5>

                    <div class="xs12">
                        <div class="text-field text-field--filled {{ $errors->has('name') ? 'text-field--helper-text text-field--invalid' : '' }}">
                            <input id="name" type="text" class="text-field__input" name="name" value="{{ old('name') ?? $warehouse->name }}" required autofocus>
                            <label for="name" class="text-field__label">{{ __('model.name', ['model' => trans_choice('model.Warehouse', 1)]) }}*</label>

                            @if ($errors->has('name'))
                                <span class="text-field__helper-text" role="alert">
                                    {{ $errors->first('name') }}
                                </span>
                            @endif
                        </div>
                    </div>
                </div>
            </div>

            <div class="xs12">
                <button type="submit" class="button button--contained button--contained--icon-left">
                    <i class="material-icons icon">save</i>
                    {{ __('model.edit', ['model' => trans_choice('model.Warehouse', 1)]) }}
                </button>

                <button type="reset" class="button button--text button--text--icon-left">
                    <i class="material-icons icon">settings_backup_restore</i>
                    {{ __('model.reset') }}
                </button>
            </div>
        </div>
    </form>
@endsection

resources/views/warehouses/index.blade.php
@extends('layouts.app')
@section('title', trans_choice('model.Warehouse', 2))

@section('content')
    <div class="row">
        @include('partials.create-button')

        @include('partials.filter',
            [
                'items' => $warehouses,
                'fields' => [
                    'id' => __('model.Id'),
                    'name' => __('model.Name'),
                    'user_created' => __('model.Creator'),
                    'user_updated' => __('model.Updater'),
                    'created_at' => __('model.Created at'),
                    'updated_at' => __('model.Updated at'),
                ]
            ]
        )

        @include('partials.pagination', ['items' => $warehouses])

        <div class="xs12">
            @if($warehouses->count() > 0)
                <table class="data-table data-table--hover data-table--responsive">
                    <thead>
                    <tr>
                        <th>{{ __('model.name', ['model' => trans_choice('model.Warehouse', 1)]) }}</th>
                        <th class="data-table--numeric">{{ trans_choice('model.Rack', 2) }}</th>
                        <th class="data-table--numeric">{{ trans_choice('model.Shelf', 2) }}</th>
                        <th class="md-down-hide">{{ __('model.Created by') }}</th>
                        <th class="md-down-hide">{{ __('model.Updated by') }}</th>
                        <th>{{ __('model.Actions') }}</th>
                    </tr>
                    </thead>

                    <tbody>
                        @foreach($warehouses as $warehouse)
                            <tr>
                                <td>{{ $warehouse->name }}</td>
                                <td class="data-table--numeric">{{ $warehouse->racks ? $warehouse->racks->count() : '' }}</td>
                                <td class="data-table--numeric">{{ $warehouse->shelves ? $warehouse->shelves->count() : '' }}</td>
                                <td class="md-down-hide">{{ $warehouse->creator->first_name }}</td>
                                <td class="md-down-hide">{{ $warehouse->updater ? $warehouse->updater->first_name : '' }}</td>
                                <td>
                                    @include('partials.actions',
                                        [
                                            'item' => $warehouse,
                                            'actions' => ['edit', 'delete']
                                        ]
                                    )
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>

            @else
                @include('partials.not-found-banner', ['model' => trans_choice('model.warehouse', 2)])
            @endif
        </div>

        @include('partials.pagination', ['items' => $warehouses])
    </div>
@endsection;