routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
})->name('home');

Auth::routes();

Route::group(['prefix' => 'dashboard', 'middleware' => 'auth'], function() {
    Route::get('/', 'DashboardController@index')->name('dashboard.index');
    Route::get('manual', 'DashboardController@manual')->name('dashboard.manual');

    Route::resource('users', 'UserController');

    Route::resource('roles', 'RoleController');

    Route::resource('parts', 'PartController');

    Route::resource('customers', 'CustomerController');

    Route::resource('warehouses', 'WarehouseController');

    Route::resource('racks', 'RackController');

    Route::resource('shelves', 'ShelfController');

    Route::resource('suppliers', 'SupplierController');

    Route::resource('statuses', 'StatusController');

    Route::resource('orders', 'OrderController');

    Route::get('cart', 'CartController@index')->name('cart.index');
    Route::get('cart/{part}/edit', 'CartController@edit')->name('cart.edit');
    Route::post('cart/{part}/add', 'CartController@add')->name('cart.add');
    Route::put('cart/{part}', 'CartController@update')->name('cart.update');
    Route::delete('cart/{part}', 'CartController@destroy')->name('cart.destroy');

    Route::resource('assignments', 'AssignmentController');
    Route::get('assignments/{assignment}/export', 'AssignmentController@export')->name('assignment.export');

    Route::resource('tasks', 'TaskController');

    Route::resource('categories', 'CategoryController');

    Route::get('time-registrations', 'TimeRegistrationController@index')->name('time-registrations.index');
    Route::post('time-registrations', 'TimeRegistrationController@store')->name('time-registrations.store');
    Route::get('time-registrations/{assignment}/create/', 'TimeRegistrationController@create')->name('time-registrations.create');
    Route::get('time-registrations/{time_registration}', 'TimeRegistrationController@show')->name('time-registrations.show');
    Route::put('time-registrations/{time_registration}', 'TimeRegistrationController@update')->name('time-registrations.update');
    Route::delete('time-registrations/{time_registration}', 'TimeRegistrationController@destroy')->name('time-registrations.destroy');
    Route::get('time-registrations/{time_registration}/edit', 'TimeRegistrationController@edit')->name('time-registrations.edit');

    Route::get('used-parts', 'UsedPartController@index')->name('used-parts.index');
    Route::post('used-parts/{assignment}', 'UsedPartController@store')->name('used-parts.store');
    Route::get('used-parts/{assignment}/create/', 'UsedPartController@create')->name('used-parts.create');
    Route::put('used-parts/{used_part}', 'UsedPartController@update')->name('used-parts.update');
    Route::delete('used-parts/{used_part}', 'UsedPartController@destroy')->name('used-parts.destroy');
    Route::get('used-parts/{used_part}/edit', 'UsedPartController@edit')->name('used-parts.edit');

    Route::resource('units', 'UnitController');
});

app/Unit.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Unit extends Model
{
    protected $fillable = [ 'name', 'abbreviation', 'user_created', 'user_updated' ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function parts()
    {
        return $this->hasMany( Part::class );
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function creator()
    {
        return $this->belongsTo( User::class, 'user_created' );
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function updater()
    {
        return $this->belongsTo( User::class, 'user_updated' );
    }

    /**
     * @param $query
     * @param $q
     *
     * @return mixed
     */
    public function scopeSearch( $query, $q )
    {
        if( $q === null )
        {
            return $query;
        }

        return $query->where( 'id', 'LIKE', "%{$q}%" )
                     ->orWhere( 'name', 'LIKE', "%{$q}%" )
                     ->orWhere( 'abbreviation', 'LIKE', "%{$q}%" );
    }
}

app/Http/Controllers/UnitController.php
<?php

namespace App\Http\Controllers;

use App\Unit;
use Illuminate\Http\Request;

class UnitController extends Controller
{
    function __construct()
    {
        $this->middleware( 'permission:view units', [ 'only' => [ 'index' ] ] );
        $this->middleware( 'permission:create units', [ 'only' => [ 'create', 'store' ] ] );
        $this->middleware( 'permission:edit units', [ 'only' => [ 'edit', 'update' ] ] );
        $this->middleware( 'permission:delete units', [ 'only' => [ 'destroy' ] ] );
    }

    /**
     * Display a listing of the resource.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \App\Unit[]|\Illuminate\Database\Eloquent\Collection
     */
    public function index( Request $request )
    {
        $sortBy = $request->sort ? $request->sort : 'name';
        $orderBy = $request->order ? $request->order : 'asc';
        $perPage = $request->perPage ? $request->perPage : 20;
        $q = $request->q ? $request->q : null;

        $units = Unit::search( $q )->orderBy( $sortBy, $orderBy )->paginate( $perPage );

        return view( 'units.index', compact( 'units', 'sortBy', 'orderBy', 'perPage', 'q' ) );
    }

    /**
     * Show the form for creating a new resource.
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view( 'units.create' );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param \App\Unit $unit
     *
     * @return \Illuminate\Http\Response
     */
    public function show( Unit $unit )
    {
        return view( 'units.show', compact( 'unit' ) );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store( Request $request )
    {
        $request->merge( [
            'step', str_replace( ',', '.', $request->step ),
            'user_created' => auth()->user()->id,
        ] );
        $this->validation( $request );

        $stored = Unit::create( [
            'name'         => $request->name,
            'abbreviation' => $request->abbreviation,
            'user_created' => auth()->user()->id,
        ] );

        return redirect()->route( 'units.index' )
                         ->with( [
                             'message' => __( $stored ? 'model.stored' : 'model.not_stored', [ 'model' => trans_choice( 'model.Unit', 1 ), 'name' => $request->name ] ),
                             'success' => $stored,
                         ] );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Unit $unit
     *
     * @return \Illuminate\Http\Response
     */
    public function edit( Unit $unit )
    {
        return view( 'units.edit', compact( 'unit' ) );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Unit                $unit
     *
     * @return void
     */
    public function update( Request $request, Unit $unit )
    {
        $request->merge( [
            'step', str_replace( ',', '.', $request->step ),
            'user_updated' => auth()->user()->id,
        ] );
        $this->validation( $request, $unit->id );

        $updated = $unit->update( $request->all() );

        return redirect()->route( 'units.index' )
                         ->with( [
                             'message' => __( $updated ? 'model.updated' : 'model.not_updated', [ 'model' => trans_choice( 'model.Unit', 1 ), 'name' => $request->name ] ),
                             'success' => $updated,
                         ] );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Unit $unit
     *
     * @return void
     * @throws \Exception
     */
    public function destroy( Unit $unit )
    {
        $deleted = $unit->delete();

        return redirect()->route( 'units.index' )
                         ->with( [
                             'message' => __( $deleted ? 'model.deleted' : 'model.not_deleted', [ 'model' => trans_choice( 'model.Unit', 1 ), 'name' => $unit->name ] ),
                             'success' => $deleted,
                         ] );
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param Int|null                 $id
     *
     * @return array|void
     */
    private function validation( Request $request, Int $id = null )
    {
        $request->validate( [
            'name'         => 'required|string|max:255|'.$id ? 'unique:units,name,'.$id : 'unique:units',
            'abbreviation' => 'required|string',
        ] );
    }
}

resources/views/units/create.blade.php
@extends('layouts.app')
@section('title', __('model.add', ['model' => trans_choice('model.Unit', 1)]))

@section('content')

<form method="POST" action="{{ route('units.store') }}">
    @csrf
    <div class="row">
        <div class="xs12">
            <a href="{{ route('units.index') }}" class="button button--contained button--contained--icon-left">
                <i class="material-icons icon">arrow_back</i>
                {{ __('model.back', ['page' => trans_choice('model.unit', 2)]) }}
            </a>
        </div>

        <div class="xs12 sm6 md3">
             <div class="row padding--0">
                 <h5 class="xs12">{{ trans_choice('model.Unit', 1) }}</h5>

                <div class="xs12 md6">
                    <div class="text-field text-field--filled {{ $errors->has('name') ? 'text-field--helper-text text-field--invalid' : '' }}">
                        <input id="name" type="text" class="text-field__input" name="name" value="{{ old('name') }}" required autofocus>
                        <label for="name" class="text-field__label">{{ __('model.name', ['model' => trans_choice('model.Unit', 1)]) }}*</label>

                        @if ($errors->has('name'))
                            <span class="text-field__helper-text" role="alert">
                                {{ $errors->first('name') }}
                            </span>
                        @endif
                    </div>
                </div>

                 <div class="xs12 md6">
                     <div class="text-field text-field--filled {{ $errors->has('abbreviation') ? 'text-field--helper-text text-field--invalid' : '' }}">
                         <input id="abbreviation" type="text" class="text-field__input" name="abbreviation" value="{{ old('abbreviation') }}" required>
                         <label for="abbreviation" class="text-field__label">{{ __('model.Abbreviation') }}*</label>

                         @if ($errors->has('abbreviation'))
                             <span class="text-field__helper-text" role="alert">
                                {{ $errors->first('abbreviation') }}
                            </span>
                         @endif
                     </div>
                 </div>
             </div>
        </div>

        <div class="xs12">
            <button type="submit" class="button button--contained button--contained--icon-left">
                <i class="material-icons icon">save</i>
                {{ __('model.add', ['model' => trans_choice('model.Unit', 1)]) }}
            </button>

            <button type="reset" class="button button--text button--text--icon-left">
                <i class="material-icons icon">settings_backup_restore</i>
                {{ __('model.reset') }}
            </button>
        </div>
    </div>
</form>
@endsection

resources/views/units/edit.blade.php
@extends('layouts.app')
@section('title', __('model.edit_title', ['name' => $unit->name, 'model' => trans_choice('model.unit', 1)]))

@section('content')

    <form method="POST" action="{{ route('units.update', $unit->id) }}">
        @method('put')
        @csrf

        <div class="row">
            <div class="xs12">
                <a href="{{ route('units.index') }}" class="button button--contained button--contained--icon-left">
                    <i class="material-icons icon">arrow_back</i>
                    {{ __('model.back', ['page' => trans_choice('model.unit', 2)]) }}
                </a>
            </div>

            <div class="xs12 sm6 md3">
                <div class="row padding--0">
                    <h5 class="xs12">{{ trans_choice('model.Unit', 1) }}</h5>

                    <div class="xs12 md6">
                        <div class="text-field text-field--filled {{ $errors->has('name') ? 'text-field--helper-text text-field--invalid' : '' }}">
                            <input id="name" type="text" class="text-field__input" name="name" value="{{ old('name') ?? $unit->name }}" required autofocus>
                            <label for="name" class="text-field__label">{{ __('model.name', ['model' => trans_choice('model.Unit', 1)]) }}*</label>

                            @if ($errors->has('name'))
                                <span class="text-field__helper-text" role="alert">
                                    {{ $errors->first('name') }}
                                </span>
                            @endif
                        </div>
                    </div>

                    <div class="xs12 md6">
                        <div class="text-field text-field--filled {{ $errors->has('abbreviation') ? 'text-field--helper-text text-field--invalid' : '' }}">
                            <input id="abbreviation" type="text" class="text-field__input" name="abbreviation" value="{{ old('abbreviation') ?? $unit->abbreviation }}" required>
                            <label for="abbreviation" class="text-field__label">{{ __('model.Abbreviation') }}*</label>

                            @if ($errors->has('abbreviation'))
                                <span class="text-field__helper-text" role="alert">
                                    {{ $errors->first('abbreviation') }}
                                </span>
                            @endif
                        </div>
                    </div>
                </div>
            </div>

            <div class="xs12">
                <button type="submit" class="button button--contained button--contained--icon-left">
                    <i class="material-icons icon">save</i>
                    {{ __('model.edit', ['model' => trans_choice('model.Unit', 1)]) }}
                </button>

                <button type="reset" class="button button--text button--text--icon-left">
                    <i class="material-icons icon">settings_backup_restore</i>
                    {{ __('model.reset') }}
                </button>
            </div>
        </div>
    </form>
@endsection

resources/views/units/index.blade.php
@extends('layouts.app')
@section('title', trans_choice('model.Unit', 2))

@section('content')
    <div class="row">
        @include('partials.create-button')

        @include('partials.filter',
             [
                 'items' => $units,
                 'fields' => [
                    'id' => __('model.Id'),
                    'name' => __('model.Name'),
                    'abbreviation' => __('model.Abbreviation'),
                    'user_created' => __('model.Creator'),
                    'user_updated' => __('model.Updater'),
                    'created_at' => __('model.Created at'),
                    'updated_at' => __('model.Updated at'),
                 ]
             ]
        )

        @include('partials.pagination', ['items' => $units])

        <div class="xs12">
            @if($units->count() > 0)
                <table class="data-table data-table--hover data-table--responsive">
                    <thead>
                    <tr>
                        <th>{{ __('model.name', ['model' => trans_choice('model.Unit', 1)]) }}</th>
                        <th>{{ __('model.Abbreviation') }}</th>
                        <th class="data-table--numeric">{{ trans_choice('model.Part', 2) }}</th>
                        <th>{{ __('model.Actions') }}</th>
                    </tr>
                    </thead>

                    <tbody>
                        @foreach($units as $unit)
                            <tr>
                                <td>
                                    @can('show units')
                                        <a href="{{ route('units.show', $unit->id) }}">
                                            {{ $unit->name }}
                                        </a>
                                    @endcan

                                    @cannot('show units')
                                        {{ $unit->name }}
                                    @endcannot
                                </td>
                                <td>
                                    @can('show units')
                                        <a href="{{ route('units.show', $unit->id) }}">
                                            {{ $unit->abbreviation }}
                                        </a>
                                    @endcan

                                    @cannot('show units')
                                        {{ $unit->abbreviation }}
                                    @endcannot
                                </td>
                                <td class="data-table--numeric">{{ $unit->parts->count() }}</td>
                                <td>
                                    @include('partials.actions',
                                        [
                                            'item' => $unit,
                                            'actions' => ['edit', 'show', 'delete']
                                        ]
                                    )
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>

            @else
                @include('partials.not-found-banner', ['model' => trans_choice('model.unit', 2)])
            @endif
        </div>

        @include('partials.pagination', ['items' => $units])
    </div>
@endsection;

resources/views/units/show.blade.php
@extends('layouts.app')
@section('title', __('model.info', ['model' => trans_choice('model.Unit', 1), 'name' => $unit->name]))

@section('content')
    <div class="row">
        <div class="xs12">
            <a href="{{ route('units.index') }}" class="button button--contained button--contained--icon-left">
                <i class="material-icons icon">arrow_back</i>
                {{ __('model.back', ['page' => trans_choice('model.unit', 2)]) }}
            </a>
        </div>

        <div class="xs12 sm6 md3">
            <div class="card">
                <div class="card__header">
                    <div class="card__title">
                        <i class="material-icons icon">info</i>
                        {{ __('model.General') }}
                    </div>
                </div>

                <div class="card__text">
                    <ul class="list">
                        <li class="list--two-line">
                            <div class="list__content">
                                <span class="list__content__title">{{ __('model.name', ['model' => trans_choice('model.Unit', 1)]) }}</span>
                                <span class="list__content__text">{{ $unit->name }}</span>
                            </div>
                        </li>
                        <li class="list--two-line">
                            <div class="list__content">
                                <span class="list__content__title">{{ __('model.Abbreviation') }}</span>
                                <span class="list__content__text">{{ $unit->abbreviation }}</span>
                            </div>
                        </li>
                        <li class="list--two-line">
                            <div class="list__content">
                                <span class="list__content__title">{{ trans_choice('model.Created by', 1) }}</span>
                                <span class="list__content__text">
                                    @can('show users')
                                        <a href="{{ route('users.show', $unit->creator->id) }}">
                                            {{ $unit->creator->first_name }}
                                        </a>
                                    @endcan

                                    @cannot('show users')
                                        {{ $unit->creator->first_name }}
                                    @endcannot
                                </span>
                            </div>
                        </li>
                        <li class="list--two-line">
                            <div class="list__content">
                                <span class="list__content__title">{{ trans_choice('model.Updated by', 1) }}</span>
                                <span class="list__content__text">
                                    @if($unit->updater)
                                        @can('show users')
                                            <a href="{{ route('users.show', $unit->updater->id) }}">
                                            {{ $unit->updater->first_name }}
                                        </a>
                                        @endcan

                                        @cannot('show users')
                                            {{ $unit->updater->first_name }}
                                        @endcannot
                                    @endif
                                </span>
                            </div>
                        </li>
                    </ul>
                </div>

                @can('edit units')
                    <div class="card__actions">
                        <a href="{{ route('units.edit', $unit->id) }}" class="button button--text">
                            {{ __('model.edit', ['model' => trans_choice('model.Unit', 1)]) }}
                        </a>
                    </div>
                @endcan
            </div>
        </div>

        <div class="xs12 md7 lg5">
            <div class="card">
                <div class="card__header">
                    <div class="card__title">
                        @can('view parts')
                            <a href="{{ route('parts.index') }}">
                                <i class="material-icons icon">build</i>
                                {{ trans_choice('model.Part', 2) }}
                            </a>
                        @endcan

                        @cannot('view parts')
                            <i class="material-icons icon">build</i>
                            {{ trans_choice('model.Part', 2) }}
                        @endcannot
                    </div>
                </div>

                <div class="card__text">
                    @if( $unit->parts->count() > 0 )
                        <table class="data-table data-table--hover">
                            <thead>
                            <tr>
                                <th>{{ trans_choice('model.Part', 1) }}</th>
                                <th>{{ __('model.Gross price') }}</th>
                                <th class="data-table--numeric">{{ __('model.Stock') }}</th>
                            </tr>
                            </thead>

                            <tbody>
                            @foreach($unit->parts as $part)
                                <tr>
                                    <td>
                                        @can('show parts')
                                            <a href="{{ route('parts.show', $part->id) }}">
                                                {{ $part->name }}
                                            </a>
                                        @endcan

                                        @cannot('show parts')
                                            {{ $part->name }}
                                        @endcannot
                                    </td>
                                    <td>&euro;{{ number_format($part->price, 2, ',', '.') }}</td>

                                    @php
                                        $stock = 0;
                                        for($i = 0; $i < count($part->shelves); $i++)
                                        {
                                            $stock += $part->shelves[$i]->pivot->stock;
                                        }
                                    @endphp

                                    <td class="data-table--numeric {{ $stock < $part->minimal_stock ? 'red-50 text--red-900' : 'green-50 text--green-900' }}">
                                        {{  $stock }} /
                                        {{ $part->minimal_stock }} {{ $part->unit->abbreviation }}
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    @else
                        @include('partials.not-found-banner', ['model' => trans_choice('model.part', 2)])
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection