routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
})->name('home');

Auth::routes();

Route::group(['prefix' => 'dashboard', 'middleware' => 'auth'], function() {
    Route::get('/', 'DashboardController@index')->name('dashboard.index');
    Route::get('manual', 'DashboardController@manual')->name('dashboard.manual');

    Route::resource('users', 'UserController');

    Route::resource('roles', 'RoleController');

    Route::resource('parts', 'PartController');

    Route::resource('customers', 'CustomerController');

    Route::resource('warehouses', 'WarehouseController');

    Route::resource('racks', 'RackController');

    Route::resource('shelves', 'ShelfController');

    Route::resource('suppliers', 'SupplierController');

    Route::resource('statuses', 'StatusController');

    Route::resource('orders', 'OrderController');

    Route::get('cart', 'CartController@index')->name('cart.index');
    Route::get('cart/{part}/edit', 'CartController@edit')->name('cart.edit');
    Route::post('cart/{part}/add', 'CartController@add')->name('cart.add');
    Route::put('cart/{part}', 'CartController@update')->name('cart.update');
    Route::delete('cart/{part}', 'CartController@destroy')->name('cart.destroy');

    Route::resource('assignments', 'AssignmentController');
    Route::get('assignments/{assignment}/export', 'AssignmentController@export')->name('assignment.export');

    Route::resource('tasks', 'TaskController');

    Route::resource('categories', 'CategoryController');

    Route::get('time-registrations', 'TimeRegistrationController@index')->name('time-registrations.index');
    Route::post('time-registrations', 'TimeRegistrationController@store')->name('time-registrations.store');
    Route::get('time-registrations/{assignment}/create/', 'TimeRegistrationController@create')->name('time-registrations.create');
    Route::get('time-registrations/{time_registration}', 'TimeRegistrationController@show')->name('time-registrations.show');
    Route::put('time-registrations/{time_registration}', 'TimeRegistrationController@update')->name('time-registrations.update');
    Route::delete('time-registrations/{time_registration}', 'TimeRegistrationController@destroy')->name('time-registrations.destroy');
    Route::get('time-registrations/{time_registration}/edit', 'TimeRegistrationController@edit')->name('time-registrations.edit');

    Route::get('used-parts', 'UsedPartController@index')->name('used-parts.index');
    Route::post('used-parts/{assignment}', 'UsedPartController@store')->name('used-parts.store');
    Route::get('used-parts/{assignment}/create/', 'UsedPartController@create')->name('used-parts.create');
    Route::put('used-parts/{used_part}', 'UsedPartController@update')->name('used-parts.update');
    Route::delete('used-parts/{used_part}', 'UsedPartController@destroy')->name('used-parts.destroy');
    Route::get('used-parts/{used_part}/edit', 'UsedPartController@edit')->name('used-parts.edit');

    Route::resource('units', 'UnitController');
});

app/UsedPart.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class UsedPart extends Model
{
    protected $table = 'assignment_part';

    protected $guarded = ['id'];

    protected $casts = [
        'parts' => 'array',
        'amounts' => 'array'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function assignment()
    {
        return $this->belongsTo( Assignment::class );
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function part()
    {
        return $this->belongsTo( Part::class );
    }

    public function scopeSearch( $query, $q )
    {
        if( $q === null ) {
            return $query;
        }

        return $query->where('name', 'LIKE', "%{$q}%")
            ->orWhere('abbreviation', 'LIKE', "%{$q}%");
    }
}

app/Http/Controllers/UsedPartController.php
<?php

namespace App\Http\Controllers;

use App\UsedPart;
use App\Shelf;
use App\Assignment;
use Illuminate\Http\Request;

class UsedPartController extends Controller
{
    function __construct()
    {
        $this->middleware('permission:view used-parts', ['only' => ['index']]);
        $this->middleware('permission:create used-parts', ['only' => ['create', 'store']]);
        $this->middleware('permission:edit used-parts', ['only' => ['edit', 'update']]);
        $this->middleware('permission:show used-parts', ['only' => ['show']]);
        $this->middleware('permission:delete used-parts', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \App\UsedPart[]|\Illuminate\Database\Eloquent\Collection
     */
    public function index( Request $request )
    {
        $sortBy = $request->sort ? $request->sort : 'assignment_id';
        $orderBy = $request->order ? $request->order : 'desc';
        $perPage = $request->perPage ? $request->perPage : 20;
        $q = $request->q ? $request->q : null;

        $used_parts = UsedPart::search($q)->orderBy($sortBy, $orderBy)->paginate($perPage);

        return view( 'used-parts.index', compact( 'used_parts', 'sortBy', 'orderBy', 'perPage', 'q' ) );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param \App\Assignment $assignment
     *
     * @return \Illuminate\Http\Response
     */
    public function create( Assignment $assignment )
    {
        $shelves = Shelf::all();
        return view( 'used-parts.create', compact('assignment', 'shelves') );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Assignment          $assignment
     *
     * @return \Illuminate\Http\Response
     */
    public function store( Request $request, Assignment $assignment )
    {
        $this->validation( $request );

        /**
         * Create array for used parts
         */
        $sync = [];
        for( $i = 0; $i < count( $request->parts ); $i++ )
        {
            $part_id = explode( '_', $request->parts[$i] )[0];
            $sync[$part_id] = ['amount' => str_replace(',', '.', $request->amounts[$i])];
        }

        $assignment->parts()->attach( $sync );

        /** Create array to decrease stock */
        for( $i = 0; $i < count( $request->parts ); $i++ )
        {
            $ids = explode('_', $request->parts[$i] );
            $part_id = $ids[0];
            $shelf = Shelf::find($ids[1]);
            $stock = $shelf->parts()->where('part_id', $part_id)->first()->pivot->stock;
            $new_stock = $stock - str_replace(',', '.', $request->amounts[$i]);

            $shelf->parts()->updateExistingPivot($part_id, ['stock' => $new_stock]);
        }

        return redirect()->route('assignments.index')
            ->with('message', __('model.stored', ['model' => trans_choice('model.Used part', 2), 'name' => $assignment->name]))
            ->with('success', true);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\UsedPart $used_part
     *
     * @return \Illuminate\Http\Response
     */
    public function edit( UsedPart $used_part )
    {
        return view( 'used-parts.edit', compact( 'used_part' ) );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\UsedPart            $usedPart
     *
     * @return void
     */
    public function update( Request $request, UsedPart $usedPart )
    {
        $request->merge(['amount' => str_replace(',', '.', $request->amount)]);

        $request->validate([
            'amount' => 'required|max:10|regex:/^\d+(\.\d{2})?$/'
        ]);

        $updated = $usedPart->update([
            'amount' => $request->amount
        ]);

        if( $updated )
        {
            return redirect()->route('used-parts.index')
            ->with('message', __('model.updated', ['model' => trans_choice('model.Used part', 1), 'name' => $usedPart->part->name]))
            ->with('success', true);
        } else {
            return redirect()->route('used-parts.index')
            ->with('message', __('model.not_updated', ['model' => trans_choice('model.Used part', 1), 'name' => $usedPart->part->name]))
            ->with('success', false);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\UsedPart $used_part
     *
     * @return void
     * @throws \Exception
     */
    public function destroy( UsedPart $used_part )
    {
        $deleted = $used_part->delete();

        if( $deleted )
        {
            return redirect()->route('used-parts.index')
                ->with('message', __('model.deleted', ['model' => trans_choice('model.Time registration', 1), 'name' => $used_part->name]))
                ->with('success', true);
        } else {
            return redirect()->route('used-parts.index')
                ->with('message', __('model.not_deleted', ['model' => trans_choice('model.Time registration', 1), 'name' => $used_part->name]))
                ->with('success', false);
        }
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param Int|null                 $id
     *
     * @return array|void
     */
    private function validation( Request $request, Int $id = null )
    {
        $request->validate([
            'parts' => 'required|array',
            'parts.*' => 'exists:parts,id',
            'amounts' => 'required|array',
            'amounts.*' => 'regex:/^\d+(\.\d{1,2})?$/'
        ]);
    }
}

resources/views/used-parts/create.blade.php
@extends('layouts.app')
@section('title', __('model.add', ['model' => trans_choice('model.Used part', 2).': "'.$assignment->name.'"']))

@section('content')
    <form method="POST" action="{{ route('used-parts.store', $assignment->id) }}">
        @csrf

        <div class="row">
            <div class="xs12">
                <a href="{{ route('assignments.index') }}" class="button button--contained button--contained--icon-left">
                    <i class="material-icons icon">arrow_back</i>
                    {{ __('model.back', ['page' => trans_choice('model.assignment', 2)]) }}
                </a>
            </div>

            <div class="xs12 sm6 md3">
                <div class="row padding--0">
                    <h5 class="xs12">{{ trans_choice('model.Used part', 1) }}</h5>

                    <datalist id="part_shelf">
                        @foreach($shelves as $shelf)
                            @foreach($shelf->parts as $part)
                                @if($part->suppliers->count() > 0)
                                    @php
                                        $number = '';
                                        foreach($part->suppliers as $supplier)
                                        {
                                            if($supplier->pivot->preferred)
                                            {
                                                $number = $supplier->number;
                                            }
                                        }
                                    @endphp

                                    @if(!empty($number))
                                        <option value="{{ $part->id }}_{{ $shelf->id }}">
                                            {{ $part->name }} -
                                            {{ $number }} -
                                            {{ $shelf->rack->warehouse->name }} -
                                            {{ $shelf->rack->name }} -
                                        {{ $shelf->name }}
                                    @else
                                        <option value="{{ $part->id }}_{{ $shelf->id }}">
                                            {{ $part->name }} -
                                            {{ $shelf->rack->warehouse->name }} -
                                            {{ $shelf->rack->name }} -
                                        {{ $shelf->name }}
                                    @endif
                                @else
                                    <option value="{{ $part->id }}_{{ $shelf->id }}">
                                        {{ $part->name }} -
                                        {{ $shelf->rack->warehouse->name }} -
                                        {{ $shelf->rack->name }} -
                                       {{ $shelf->name }}
                                    </option>
                                @endif
                            @endforeach
                        @endforeach
                    </datalist>

                    <div class="xs12" id="parts">
                        @if(old('parts'))
                            @foreach(old('parts') as $part)
                                <div class="row padding--0 part">
                                    <div class="xs12 md8">
                                        <div class="text-field text-field--filled {{ $errors->has('parts') ? 'text-field--helper-text text-field--invalid' : '' }}">
                                            <input
                                                id="part-{{ $loop->index }}"
                                                type="text"
                                                list="part_shelf"
                                                class="text-field__input"
                                                name="parts[]"
                                                value="{{ old('parts') }}"
                                                required
                                            >
                                            <label for="part-{{ $loop->index }}" class="text-field__label">{{ trans_choice('model.Part', 2) }}*</label>

                                            @if ($errors->has('parts'))
                                                <span class="text-field__helper-text" role="alert">
                                                    {{ $errors->first('parts') }}
                                                </span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="xs12 md4">
                                        <div class="text-field text-field--filled {{ $errors->has('amounts') ? 'text-field--helper-text text-field--invalid' : '' }}">
                                            <input id="amount-{{ $loop->index }}"
                                                   type="number"
                                                   class="text-field__input"
                                                   name="amounts[]"
                                                   value="{{ old('amounts') ?? '0.00' }}"
                                                   min="0.00" step="0.01"
                                                   required
                                            >
                                            <label for="amount-{{ $loop->index }}" class="text-field__label">{{ __('model.Amount') }}*</label>

                                            @if ($errors->has('amounts'))
                                                <span class="text-field__helper-text" role="alert">
                                                    {{ $errors->first('amounts') }}
                                                </span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="xs12">
                                        <button class="button button--outlined delete-part" type="button">
                                            {{ __('model.delete', ['model' => trans_choice('model.Part', 1)]) }}
                                        </button>
                                    </div>

                                    <hr class="divider xs12">
                            @endforeach
                        @endif
                    </div>

                    <div class="xs12">
                        <button class="button button--outlined" type="button" id="add-part">
                            {{ __('model.add', ['model' => trans_choice('model.Part', 1)]) }}
                        </button>
                    </div>
                </div>
            </div>

            <div class="xs12">
                <button type="submit" class="button button--contained button--contained--icon-left">
                    <i class="material-icons icon">save</i>
                    {{ __('model.add', ['model' => trans_choice('model.Used part', 2)]) }}
                </button>

                <button type="reset" class="button button--text button--text--icon-left">
                    <i class="material-icons icon">settings_backup_restore</i>
                    {{ __('model.reset') }}
                </button>
            </div>
        </div>
        </div>
    </form>
@endsection

@section('js')
    <script>
        const addPart = document.getElementById('add-part');
        const partsContainer = document.getElementById('parts');
        let deleteParts = document.getElementsByClassName('delete-part');
        let parts = {{ old('parts') ? count(old('parts')) : 0 }};

        addPart.addEventListener('click', () => {
            let html = `
                <div class="xs12 md8">
                    <div class="text-field text-field--filled">
                        <input id="part-${parts}" type="text" list="part_shelf" class="text-field__input" name="parts[]" required>
                        <label for="part-${parts}" class="text-field__label">{{ trans_choice('model.Part', 1) }}*</label>
                    </div>
                </div>

                <div class="xs12 md4">
                    <div class="text-field text-field--filled">
                        <input id="amount-${parts}" type="number" min="0.00" step="0.01" class="text-field__input" name="amounts[]" required>
                        <label for="amount-${parts}" class="text-field__label">{{ __('model.Amount') }}*</label>
                    </div>
                </div>

                <div class="xs12">
                    <button class="button button--outlined delete-part" type="button">
                        {{ __('model.delete', ['model' => trans_choice('model.Part', 1)]) }}
                    </button>
                </div>

                <hr class="divider xs12">`;

            partsContainer.appendChild(document.createElement('id'));
            let lastChild = partsContainer.lastChild;
            lastChild.className = 'row padding--0 part';
            lastChild.innerHTML = html;
            parts++;

            for( let deletePart of deleteParts )
            {
                deletePart.addEventListener('click', () => {
                    let part = deletePart.closest('.part');
                    part.remove();
                });
            }
        });
    </script>
@endsection

resources/views/used-parts/edit.blade.php
@extends('layouts.app')
@section('title', __('model.edit_title', [
    'name' => $used_part->part->name,
    'model' => trans_choice('model.used part', 1)
]))

@section('content')
    <form method="POST" action="{{ route('used-parts.update', $used_part->id) }}">
        @method('put')
        @csrf

        <div class="row">
            <div class="xs12">
                <a href="{{ route('used-parts.index') }}" class="button button--contained button--contained--icon-left">
                    <i class="material-icons icon">arrow_back</i>
                    {{ __('model.back', ['page' => trans_choice('model.Used part', 2)]) }}
                </a>
            </div>

            <div class="xs12 sm6 md3">
                <div class="row padding--0">
                    <h5 class="xs12">{{ trans_choice('model.Used part', 1) }}</h5>

                    <div class="xs12">
                        <div class="text-field text-field--filled {{ $errors->has('amount') ? 'text-field--helper-text text-field--invalid' : '' }}">
                            <input id="amount" type="number" min="0.00" step="0.01" class="text-field__input" name="amount" value="{{ old('amount') ?? $used_part->amount }}" required autofocus>
                            <label for="amount" class="text-field__label">{{ __('model.Amount') }}*</label>

                            @if ($errors->has('amount'))
                                <span class="text-field__helper-text" role="alert">
                                    {{ $errors->first('amount') }}
                                </span>
                            @endif
                        </div>
                    </div>
            </div>

            <div class="xs12">
                <button type="submit" class="button button--contained button--contained--icon-left">
                    <i class="material-icons icon">save</i>
                    {{ __('model.edit', ['model' => trans_choice('model.used part', 1)]) }}
                </button>

                <button type="reset" class="button button--text button--text--icon-left">
                    <i class="material-icons icon">settings_backup_restore</i>
                    {{ __('model.reset') }}
                </button>
            </div>
        </div>
        </div>
    </form>
@endsection

resources/views/used-parts/index.blade.php
@extends('layouts.app')
@section('title', trans_choice('model.Used part', 2))

@section('content')
    <div class="row">
        @include('partials.filter',
           [
               'items' => $used_parts,
               'fields' => [
                    'id' => __('model.Id'),
                    'assignment_id' => trans_choice('model.Assignment', 1),
                    'part_id' => trans_choice('model.Part', 1),
                    'amount' => __('model.Amount')
               ]
           ]
        )

        @include('partials.pagination', ['items' => $used_parts])

        <div class="xs12">
            @if($used_parts->count() > 0)
                <table class="data-table data-table--hover data-table--responsive">
                    <thead>
                    <tr>
                        <th>{{ trans_choice('model.Assignment', 1) }}</th>
                        <th>{{ trans_choice('model.Customer', 1) }}</th>
                        <th>{{ __('model.Boat') }}</th>
                        <th>{{ trans_choice('model.Part', 1) }}</th>
                        <th class="data-table--numeric">{{ __('model.Amount') }}</th>
                        <th>{{ __('model.Actions') }}</th>
                    </tr>
                    </thead>

                    <tbody>
                        @foreach($used_parts as $used_part)
                            <tr>
                                <td>
                                    @can('show assignments')
                                        <a href="{{ route('assignments.show', $used_part->assignment->id) }}">
                                            {{ $used_part->assignment->name }}
                                        </a>
                                    @endcan

                                    @cannot('show assignments')
                                        {{ $used_part->assignment->name }}
                                    @endcannot
                                </td>
                                <td>
                                    @can('show customers')
                                        <a href="{{ route('customers.show', $used_part->assignment->customer->id) }}">
                                            {{ $used_part->assignment->customer->name }}
                                        </a>
                                    @endcan

                                    @cannot('show customers')
                                        {{ $used_part->assignment->customer->name }}
                                    @endcannot
                                </td>
                                <td>
                                    @can('show customers')
                                        <a href="{{ route('customers.show', $used_part->assignment->customer->id) }}">
                                            {{ $used_part->assignment->customer->boat }}
                                        </a>
                                    @endcan

                                    @cannot('show customers')
                                        {{ $used_part->assignment->customer->boat }}
                                    @endcannot
                                </td>
                                <td>
                                    @can('show assignments')
                                        <a href="{{ route('parts.show', $used_part->part->id) }}">
                                            {{ $used_part->part->name }}
                                        </a>
                                    @endcan

                                    @cannot('show parts')
                                        {{ $used_part->part->name }}
                                    @endcannot
                                </td>
                                <td class="data-table--numeric">
                                    {{ $used_part->amount }}
                                    {{ $used_part->part->unit->abbreviation }}
                                </td>
                                <td>
                                    @if(!$used_part->assignment->status->lock)
                                        @include('partials.actions',
                                        [
                                            'item' => $used_part,
                                            'actions' => ['edit', 'delete']
                                        ]
                                    )
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>

            @else
                @include('partials.not-found-banner', ['model' => trans_choice('model.used part', 2)])
            @endif
        </div>

        @include('partials.pagination', ['items' => $used_parts])
    </div>
@endsection;